server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}\Desktop\native-file-repo
        git:
          default-label: master
#          uri: file://C:\Users\jyr49\Desktop\git-local-repo
          uri: https://github.com/yryryr96/spring-cloud-config-test
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

